Resolves #1749
dstackai/dstack pull request #1786
Opened 2024-10-04 08:44 UTC by shradiphylleia

created a GitHub actions example to submit tasks that might require GPU.

please let me know if additional changes are needed or additional tasks could be added to make it better. Thanks

2024-10-09 17:27 UTC, shradiphylleia commented
I think the repo has received many spam PR in the last few days and that must have slowed the review process. can some reviewer let me know of any changes which I can help with this. thanks

2024-10-09 23:14 UTC, SamirPS requested changes

2024-10-09 23:14 UTC, SamirPS commented on examples/GitHub Actions/actions.yml
> +      # uncomment to install dstack if not available already
Why we don't install it by default?

2024-10-09 23:14 UTC, SamirPS commented on examples/GitHub Actions/actions.yml
> +        with:
Why 3.10 and not the last version ?

2024-10-10 08:47 UTC, peterschmidt85 commented
I wish our issues had more context. The thing is, the existing GitHub issues assume that the contributor has at least a basic understanding of how dstack works, its documentation, examples, etc. Issue #1749 is about providing an example on par with other examples – giving users a clear idea of how to use dstack with CI/CD.

The current PR doesn't seem like a useful example. Just compare it to other examples on the website.

2024-10-10 08:47 UTC, closed without merging