Fixes #1749 Add GitHub Actions example: Resolves dstackai issue #1749
dstackai/dstack pull request #2069
Opened 2024-12-08 22:29 UTC by Tob-iee

Hi guys, I created this example for the implementation of GitHub. Can you have a look and let me know if it captures what you had in mind? Although this example only shows how to use it with Kubernetes as a backend (i.e., it will typically be used for on-prem CI testing and building of AI workloads). But If it suits the idea you are thinking about I will clean it up and add the implementations for the other backend as well.

2024-12-09 14:51 UTC, peterschmidt85 commented
@Tob-iee I don't think this PR captures what is required.
1. The idea of GitHub action example is to show how to submit dstack runs as a part of GitHub Actions workflows. This implies dstack server is running somewhere else.
1.1. Your PR starts/stops server as a part of the workflow. IMO, this doesn't make sense.
2. The example implies having a page at https://dstack.ai/examples/. Your PR doesn't have it

2024-12-09 16:27 UTC, Tob-iee commented
> @Tob-iee I don't think this PR captures what is required.
> 
> 1. The idea of GitHub action example is to show how to submit dstack runs as a part of GitHub Actions workflows. This implies dstack server is running somewhere else.
>    1.1. Your PR starts/stops server as a part of the workflow. IMO, this doesn't make sense.
> 2. The example implies having a page at https://dstack.ai/examples/. Your PR doesn't have it

1. So maybe it's the way that I thought about the example initially. My assumption is that the dstack server runs on where its backend is configured. So typically the idea became that this sample example shows a "continuous deployment" workflow, where the user leverages Dstack in their github actions workflow to automate the deployment of the model on their GPU infrastructure that is on-prem. Which is why I used Kubernetes as the backend.
     1.1. Yes, you are right. I will exclude stopping the server after submitting the deployment run.
2. I will add the page

2024-12-11 14:23 UTC, peterschmidt85 commented
> My assumption is that the dstack server runs on where its backend is configured. So typically the idea became that this sample example shows a "continuous deployment" workflow, where the user leverages Dstack in their github actions workflow to automate the deployment of the model on their GPU infrastructure that is on-prem. 

Indeed, a dstack server is started where the backend is configured. But, it's not GitHub Actions.

>   1.1. Yes, you are right. I will exclude stopping the server after submitting the deployment run.

Typically, a dstack server is deployed somewhere centrally where the entire team can access it.
Starting server inside GitHub Actions makes no sense.

BTW, in a real scenario (and we can mention that in the example explicitly), the server is running in a private network and if that's the case, GitHub Actions should be configured so that it has access to the private network where the server is running.

> * I will add the page

The page itself is the main asset. Check other pages to understand what level of details and what style is required.
Basically, it should provide minimum but enough information to understand.

2024-12-18 20:59 UTC, Tob-iee commented
> > My assumption is that the dstack server runs on where its backend is configured. So typically the idea became that this sample example shows a "continuous deployment" workflow, where the user leverages Dstack in their github actions workflow to automate the deployment of the model on their GPU infrastructure that is on-prem.
> 
> Indeed, a dstack server is started where the backend is configured. But, it's not GitHub Actions.
> 
> > 1.1. Yes, you are right. I will exclude stopping the server after submitting the deployment run.
> 
> Typically, a dstack server is deployed somewhere centrally where the entire team can access it. Starting server inside GitHub Actions makes no sense.
> 
> BTW, in a real scenario (and we can mention that in the example explicitly), the server is running in a private network and if that's the case, GitHub Actions should be configured so that it has access to the private network where the server is running.
> 
> > * I will add the page
> 
> The page itself is the main asset. Check other pages to understand what level of details and what style is required. Basically, it should provide minimum but enough information to understand.

I have added an examples page to help explain the example. However, the summary of the examples use-case is:

You are automating the MLOps CI pipeline using GitHub actions for your in-built MLOps platform or a typical MLOps pipeline. The main idea is that you need your data scientist or ML engineer's ML task, which could be like a fine-tuning, training job, or inference app engine to use a GPU infrastructure because such a job (i.e., AI workload in this case) requires running on a GPU infrastructure because of the expensive computation. Your machine with GPU infrastructure could be on-prem or remote. However, either way, you already have a Dstack server running on the machine to manage and configure your GPU for your AI workloads. So each time the ML engineer or data scientist makes updates to their training component (which could be a script or YAML file) and pushes those changes so that they can execute the AI task, Dstack will automatically run it with the Dstack provisioned GPU infrastructure.

What do you think about the use case/senario?

2024-12-19 16:21 UTC, peterschmidt85 requested changes

2024-12-19 16:21 UTC, peterschmidt85 commented on examples/misc/github-actions/.dstack.yml
> +      - name: Run Dstack server and capture token
We agreed that the server is running outside of GitHub Actions

2024-12-19 16:21 UTC, peterschmidt85 commented on examples/misc/github-actions/.dstack.yml
> +          git clone https://github.com/dstackai/dstack
Why do we need some repo if we are already inside our repo with GitHub Actions?

2024-12-19 16:21 UTC, peterschmidt85 commented on examples/misc/github-actions/.dstack.yml
> +name: Run dstack Task on GPU
Also why the file is named .dstack.yml if it's a GitHub Actions file? I suppose GitHub Actions workflows files should be under .github/workflows

2024-12-19 16:21 UTC, peterschmidt85 commented on examples/misc/github-actions/README.md
> +              install -m 600 -D /dev/null ~/.ssh/github-actions
What is going on here?

2024-12-19 16:21 UTC, peterschmidt85 commented on examples/misc/github-actions/README.md
> +          - name: Clone pull new chances of your repo with AI workload code
No idea what is going on here to be honest

2024-12-20 07:42 UTC, peterschmidt85 requested changes
It seems like there might be some misunderstanding about how GitHub Actions work.

A couple of key points:

There's no need to clone any repositories—GitHub Actions handles that automatically.
Please avoid submitting untested code, whether for this repo or any other.
Given these issues, I have to reject this PR for now. Let me know if you need clarification or guidance—I’m happy to help!

2024-12-20 07:42 UTC, peterschmidt85 commented on examples/misc/github-actions/README.md
> +        run: |
What does this step do?

2024-12-20 07:42 UTC, peterschmidt85 commented on examples/misc/github-actions/README.md
> +          ssh github-actions << 'EOF'
Why is this needed?

2024-12-20 07:42 UTC, peterschmidt85 commented on examples/misc/github-actions/README.md
> +            dstack apply -f <path to dstack in your repo directory> --yes &
Doesn't look as working code

2024-12-20 07:42 UTC, closed without merging