Issue 933 ssh config fix
dstackai/dstack pull request #934
Opened 2024-02-26 23:39 UTC by spott

A set of changes to enable people with weird SSH configs to work.

2024-02-27 09:19 UTC, Egor-S requested changes

2024-02-27 09:19 UTC, Egor-S commented on gateway/src/dstack/gateway/services/tunnel.py
You should not change this file. It is not a part of a CLI (`src/dstack/_internal/cli`). `dstack-gateway` is a separate package deployed on a gateway instance. There is no custom SSH config

2024-02-27 09:19 UTC, Egor-S commented on runner/internal/gateway/ssh.go
This code is not used anymore. `dstack-gateway` opens a connection to the `dstack-runner`

2024-02-27 09:19 UTC, Egor-S commented on src/dstack/_internal/server/services/ssh/__init__.py
It's a server code and config manager is supposed to be used by CLI. I guess it's better to use `-F none` here

2024-02-27 14:28 UTC, spott commented on gateway/src/dstack/gateway/services/tunnel.py
Should we change it to `-F none` if there is no custom SSH config?

2024-02-27 14:31 UTC, spott commented on src/dstack/_internal/server/services/ssh/__init__.py
Done.

2024-02-27 14:31 UTC, Egor-S commented on gateway/src/dstack/gateway/services/tunnel.py
We can, but actually there isn't any config — it's a dedicated instance fully managed by dstack

2024-02-27 14:35 UTC, spott commented on runner/internal/gateway/ssh.go
I'm not sure what I should do here... if it is unused, should I delete it?

2024-02-27 14:36 UTC, spott commented on gateway/src/dstack/gateway/services/tunnel.py
I changed it to `-F none`.  Let me know if you think something else should be done.

2024-02-27 16:29 UTC, peterschmidt85 commented
@spott I've pushed some changes. Please let me know if all looks good to you.
cc @Egor-S

2024-02-27 16:43 UTC, peterschmidt85 requested changes
Left the comment about handling the permission error. Please let me know what you think.

2024-02-27 16:43 UTC, peterschmidt85 commented on src/dstack/_internal/utils/ssh.py
> +            try:
@spott 
Not sure about this one. Isn't it better not to catch the exception and let the user see it as is? I doubt the user will find it convenient to manually update the config and add the include.

Also, for this permission problem, we need to file a separate issue.

2024-02-27 16:57 UTC, peterschmidt85 commented on src/dstack/_internal/utils/ssh.py
> +            try:
Also, it's important to update the `update_ssh_config` function too.

2024-02-28 09:48 UTC, Egor-S commented on src/dstack/_internal/utils/ssh.py
> +                print(f"Couldn't write to {ssh_config_path} due to a permissions problem")
@peterschmidt85 
We've discussed that a logger is a better option there. But the default logging level is CRITICAL, so we need to change it in `src/dstack/_internal/cli/utils/common.py : configure_logging`

2024-02-28 09:49 UTC, Egor-S approved these changes

2024-02-28 11:30 UTC, merged